name: Test on Multiple OS

# Ejecutar cuando se realice un push o pull request a la rama 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Esta línea habilita el botón "Run workflow" en GitHub

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
    # Usar la acción de checkout para clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Python en la versión especificada
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Instalar las dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Ejecutar las pruebas o comandos necesarios
    - name: Run tests
      run: |
        python main.py  # Cambia esto a lo que quieras ejecutar
